//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pharmacy_DBEntities : DbContext
    {
        public Pharmacy_DBEntities()
            : base("name=Pharmacy_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerInformation> CustomerInformation { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<MedicineInformation> MedicineInformation { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
        public virtual DbSet<CustomerInformationView> CustomerInformationView { get; set; }
        public virtual DbSet<MedicineInformationView> MedicineInformationView { get; set; }
        public virtual DbSet<SalesInformation> SalesInformation { get; set; }
        public virtual DbSet<SalesInformationDetails> SalesInformationDetails { get; set; }
        public virtual DbSet<SalesInformationView> SalesInformationView { get; set; }
    }
}
