//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInformationView
    {
        public int SalesID { get; set; }
        public string SalesName { get; set; }
        public string InvoiceNo { get; set; }
        public string CustomerName { get; set; }
        public int CustomerID { get; set; }
        public decimal DiscountRate { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TaxPercentage { get; set; }
        public decimal TotalTax { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalPriceExcludingAll { get; set; }
        public decimal TotalPriceIncludingAll { get; set; }
    }
}
